project_id = "tqtljccgtkuicyobjwon"

[functions.school-matcher]
verify_jwt = false

[functions.school-generator]
verify_jwt = false

[functions.interview-coach]
verify_jwt = false

[functions.improve-chances]
verify_jwt = false
