// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-schools.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-schools.ts
var SELECT = "id,name,city,state,type,boarding,admission_type,tuition,acceptance_rate,enrollment,overall_grade,overall_score,website";
var search_schools_default = defineTool({
  name: "search_schools",
  title: "Search schools",
  description: "Search the high school directory by name, city, state, type, boarding status, and max tuition.",
  inputSchema: {
    query: z.string().trim().optional().describe("Text to match against the school name."),
    state: z.string().trim().length(2).optional().describe("Two-letter US state code, e.g. NY."),
    city: z.string().trim().optional().describe("City name."),
    type: z.string().trim().optional().describe("School type, e.g. Private, Magnet, Boarding."),
    boarding: z.boolean().optional().describe("Only boarding schools when true."),
    maxTuition: z.number().positive().optional().describe("Maximum annual tuition in USD."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, state, city, type, boarding, maxTuition, limit }) => {
    const supabase = supabaseAnon();
    let q = supabase.from("schools").select(SELECT);
    if (query) q = q.ilike("name", `%${query}%`);
    if (state) q = q.ilike("state", state);
    if (city) q = q.ilike("city", `%${city}%`);
    if (type) q = q.ilike("type", `%${type}%`);
    if (typeof boarding === "boolean") q = q.eq("boarding", boarding);
    if (maxTuition) q = q.lte("tuition", maxTuition);
    const { data, error } = await q.order("overall_score", { ascending: false, nullsFirst: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { schools: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-school.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_school_default = defineTool2({
  name: "get_school",
  title: "Get school profile",
  description: "Fetch the full profile for one school by its id, including grades, stats, and verification status.",
  inputSchema: { id: z2.string().uuid().describe("School id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("schools").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: `No school found with id ${id}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { school: data }
    };
  }
});

// src/lib/mcp/tools/list-saved-schools.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_saved_schools_default = defineTool3({
  name: "list_saved_schools",
  title: "List saved schools",
  description: "List the schools the signed-in user has saved to their list.",
  inputSchema: {
    category: z3.string().trim().optional().describe("Filter by list category, e.g. reach, target, safety.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("saved_schools").select("id,category,created_at,schools(id,name,city,state,type,tuition,overall_grade)").eq("user_id", ctx.getUserId());
    if (category) q = q.eq("category", category);
    const { data, error } = await q.order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { saved: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-school.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var save_school_default = defineTool4({
  name: "save_school",
  title: "Save a school",
  description: "Add a school to the signed-in user's saved list, optionally with a category.",
  inputSchema: {
    school_id: z4.string().uuid().describe("School id to save."),
    category: z4.string().trim().optional().describe("Optional list category, e.g. reach, target, safety.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ school_id, category }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("saved_schools").insert({ user_id: ctx.getUserId(), school_id, category: category ?? null }).select("id,school_id,category").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { saved: data }
    };
  }
});

// src/lib/mcp/tools/remove-saved-school.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var remove_saved_school_default = defineTool5({
  name: "remove_saved_school",
  title: "Remove a saved school",
  description: "Remove a school from the signed-in user's saved list.",
  inputSchema: { school_id: z5.string().uuid().describe("School id to remove.") },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true },
  handler: async ({ school_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("saved_schools").delete().eq("user_id", ctx.getUserId()).eq("school_id", school_id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Removed school ${school_id} from saved list.` }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tqtljccgtkuicyobjwon";
var mcp_default = defineMcp({
  name: "preppath-ai",
  title: "PrepPath AI",
  version: "0.1.0",
  instructions: "Tools for PrepPath AI, a high school discovery and application platform. Use `search_schools` and `get_school` to explore the school directory, and `list_saved_schools`, `save_school`, and `remove_saved_school` to manage the signed-in user's school list.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_schools_default,
    get_school_default,
    list_saved_schools_default,
    save_school_default,
    remove_saved_school_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
